# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.

# WE KNOW, IN THIS UNIVERSE, 1 AND 1 ARE ALWAYS THE FRIST 2 # OF THE FIB SEQUENCE
fib1 = 1
fib2 = 1
sumTotal = 0
# userAnswer = int(raw_input("What's your max: "))
# print userAnswer
# for num in range(userAnswer):
while (sumTotal < 4000000):
    if(fib1 % 2 == 0):
        sumTotal += fib1
    temp = fib1 + fib2 #stash the new value in temp
    fib1 = fib2 # old 2 is now the new 1
    fib2 = temp # temp is the new 2
    print fib2
print sumTotal


# Khanh and crew
fibSeq = [0, 1]
i = 1
sum = 0
while fibSeq[-1] < 4000000:
   fibSeq.append(fibSeq[i] + fibSeq[i - 1])
   i += 1
del fibSeq[-1]
print fibSeq
for i in fibSeq[1:len(fibSeq)]:
   if i % 2 == 0:
       sum += i
print sum
